name: maplibre
description: "Unofficial MapLibre bindings for Flutter"
version: 0.1.0
repository: https://github.com/josxha/flutter_maplibre
issue_tracker: https://github.com/josxha/flutter_maplibre/issues
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.2
  geotypes: ^0.0.2
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  pigeon: ^22.0.0
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.josxha.maplibre
        pluginClass: MapLibrePlugin
      ios:
        pluginClass: MaplibrePlugin
      linux:
        pluginClass: MaplibrePlugin
      macos:
        pluginClass: MaplibrePlugin
      windows:
        pluginClass: MaplibrePluginCApi
      web:
        pluginClass: MapLibreWeb
        fileName: src/web/web.dart
